backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /img

collections:
  - name: "crew"
    label: "Crew"
    folder: "content/crew"
    format: "frontmatter"
    create: true
    identifier_field: name
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      # - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          choose_url: true,
        }
